#!/bin/bash
# Profile fltr with Instruments Allocations template

set -e

echo "=== Building release binary ==="
swift build -c release
echo ""

echo "=== Instruments Memory Profiling ==="
echo ""
echo "Step 1: Open Instruments manually:"
echo "  open -a Instruments"
echo ""
echo "Step 2: Choose 'Allocations' template"
echo ""
echo "Step 3: In Instruments toolbar:"
echo "  - Click 'Choose Target' dropdown"
echo "  - Select '.build/release/fltr'"
echo "  - Click Record (red button)"
echo ""
echo "Step 4: In Terminal (NOT Instruments), run:"
echo "  cat find.txt | ./.build/release/fltr"
echo ""
echo "Step 5: Wait ~3 seconds for load, then press Ctrl+C in fltr terminal"
echo ""
echo "Step 6: In Instruments, click Stop recording"
echo ""
echo "Step 7: Analysis:"
echo "  - Click 'All Heap & Anonymous VM'"
echo "  - Sort by 'Persistent Bytes' (largest first)"
echo "  - Look for large allocations"
echo "  - Common culprits:"
echo "    * Array storage"
echo "    * String storage"
echo "    * Closure contexts"
echo "    * Actor storage"
echo ""
echo "Alternative: Simpler approach with leaks command"
echo "Run: ./profile_heap.sh"
echo ""
